### ISSUE TITLE
mark

### ISSUE THREAD

**Issue by lixiangcog** [ThisGame42/CTTA#1]

**Comment by ThisGame42** [comment]
Intention unclear. You are welcome to reopen with a proper description of your issue/request. Cheers.

**Comment by lixiangcog** [comment]
Where to get your paper and when will the source code come?
@ThisGame42

**Comment by ThisGame42** [comment]
The paper will be presented at MICCAI 2023, and the source code will be released once the review for our journal extension is complete.

**Comment by lixiangcog** [comment]
look forward to 😀
